version: "3.9"

networks:
  lablan:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24

services:
  web-01:
    image: cassiekeza/bookiverse:v1
    container_name: web-01
    hostname: web-01
    networks:
      lablan:
        ipv4_address: 172.20.0.11
    ports:
      - "2211:22"
      - "9000:8000"

  web-02:
    image: cassiekeza/bookiverse:v1
    container_name: web-02
    hostname: web-02
    networks:
      lablan:
        ipv4_address: 172.20.0.12
    ports:
      - "2212:22"
      - "9001:8000"

  lb-01:
    build: ./lb
    container_name: lb-01
    hostname: lb-01
    networks:
      lablan:
        ipv4_address: 172.20.0.10
    ports:
      - "2210:22"
      - "9002:8000"
